export { default as Dashboard } from './Dashboard'
export { default as Leads } from './Leads'
export { default as Login } from './Login'
export { default as Recruiters } from './Recruiters'
export { default as Settings } from './Settings'
export { default as Statistics } from './Statistics'
